export const SET_DOWNLOAD_DATA = "SET_DOWNLOAD_DATA";

export const INVERT_IS_DRAWER_OPEN = "INVERT_IS_DRAWER_OPEN";

export const SET_USER = "LOGIN";

export const SELECT_GENRE = "SELECT_GENRE";
export const SELECT_MEMO = "SELECT_MEMO";
export const SELECT_SEARCH_RESULT_MEMO = "SELECT_SEARCH_RESULT_MEMO"; //SELECT_MEMOと違い、選択しているジャンルのすべての子のメモを対象にしている
export const DESELECT_MEMO = "DESELECT_MEMO";

export const ADD_MEMO = "ADD_MEMO";
export const DELETE_MEMO = "DELETE_MEMO";
export const EDIT_MEMO = "EDIT_MEMO";
export const INCREMENT_NEXT_MEMO_ID = "INCREMENT_NEXT_MEMO_ID";
export const DECREMENT_NEXT_MEMO_ID = "DECREMENT_NEXT_MEMO_ID";
export const SET_NEXT_MEMO_ID = "SET_NEXT_MEMO_ID";

export const SET_FILTER_TEXT = "SET_FILTERTEXT";

export const ADD_GENRE = "ADD_GENRE";
export const DELETE_GENRE = "DELETE_GENRE";
export const EDIT_GENRE = "EDIT_GENRE";
export const INCREMENT_NEXT_GENRE_ID = "INCREMENT_NEXT_GENRE_ID";
export const DECREMENT_NEXT_GENRE_ID = "DECREMENT_NEXT_GENRE_ID";
export const SET_NEXT_GENRE_ID = "SET_NEXT_GENRE_ID";
